export { default as SignUpImg1 } from "../assets/social-logo.svg";
export { default as SignUpImg2 } from "../assets/social-logo (1).svg";
export { default as Singleimgproba } from "../assets/singleimg.png";
export { default as MenuBook } from "../assets/Menu book.svg";
export { default as PersonImg } from "../assets/Person.svg";
export { default as AccaunBalanceImg } from "../assets/Account balance wallet.svg";
export { default as SettingsImgSL } from "../assets/Settings.svg";
export { default as EmailImgL } from "../assets/Email.svg";
export { default as Piechartimg } from "../assets/Pie chart.svg";
export { default as ChatbubbleImg } from "../assets/Chat bubble.svg";
export { default as SearchImg } from "../assets/Search.svg";
export { default as GroupImg } from "../assets/Group 2.svg";
export { default as GroupImg2 } from "../assets/Group 2 (1).svg";
export { default as GroupImg3 } from "../assets/Group 2 (2).svg";
export { default as GroupImg4 } from "../assets/Group 2 (3).svg";
export { default as UnsplashImg } from "../assets/unsplash_WNoLnJo7tS8.svg";
export { default as NotificationImg } from "../assets/Notifications none.svg";
export { default as decreaseImg } from "../assets/decrease.svg";
export { default as increseImg } from "../assets/increse.svg";
export { default as pizzaimg } from "../assets/Pepperoni-Pizza 1.png";
export { default as rightSI1P } from "../assets/toppng 1.png";
export { default as rightSI2P } from "../assets/toppng 2.png";
export { default as pngaaaimg } from "../assets/pngaaa 1.png";
export { default as Pepperoniimgpizza } from "../assets/Pepperoni-Pizza 1.png";